- hosts: localhost
  become: true
  tasks:
#  - name: Install htop
#    apt: name=htop
#  - name: Install tilix
#    apt: name=tilix
#  - name: Install Git
#    apt: name=git
  - name: neofetch
    apt: name=neofetch